# Generated by Django 3.2.7 on 2021-09-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ms_old_price',
            new_name='md_old_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ms_price',
            new_name='md_price',
        ),
    ]
