# Generated by Django 3.2.7 on 2021-09-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_category_name_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
