# Generated by Django 3.2.7 on 2021-10-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_demonsions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='demonsions',
            field=models.CharField(blank=True, choices=[('sm', '25x40cm'), ('md', '40x70cm'), ('lg', '80x120cm')], max_length=2, null=True),
        ),
    ]
